### ISSUE TITLE
如何集成到hubot里？

### ISSUE THREAD

**Issue by xiaomingplus** [KasperDeng/Hubot-WeChat#1]
貌似教程都不够详细...不太会使用..而且也没在npm里？

**Comment by yuanbohan** [comment]
hi，是否有进展呢

**Comment by xiaomingplus** [comment]
没有...在等开发者回复呢。

**Comment by KasperDeng** [comment]
增加了中文版本的README。hubot-weixin 已经提交到npm里面了，最新版本是1.0.0。 
https://www.npmjs.com/package/hubot-weixin

**Comment by xiaomingplus** [comment]
thanks,已调试成功，不过登录网页版微信拿到cokkie等信息后，最好退出网页版，不然消息丢包的情况非常严重。

**Comment by KasperDeng** [comment]
哦，可能跟所在网络有关系？我倒没遇到什么问题。可能我所以的网络比较强大的缘故。
有空你研究下代码或者看看后端的脚本可以做什么事情。给点建议。谢谢！
