### ISSUE TITLE
群聊如果仅回复@robot的消息，请问应该从哪里改呀？

### ISSUE THREAD

**Issue by lihk11** [KasperDeng/Hubot-WeChat#10]
群聊如果仅回复@robot的消息，请问应该从哪里改？并且单独聊的时候不需要加@或者机器人的名字，貌似在script里很难实现。。。

**Comment by xxlv** [comment]
这个貌似是你的逻辑吧，匹配到  @robot(.*?)  ，对匹配的结果处理不就ok了？

**Comment by KasperDeng** [comment]
* 可以根据后端的script进行定制
   - `robot.hear`：不需要加对话前加`[@]robot`，只要匹配到你设定的正则表达式即可触发后端的动作。
   - `robot.respond`：跟`robot.hear`相反。
   - `robot.messageRoom`：robot主动发送消息到指定的room/群。

**Comment by lihk11** [comment]
实际上是分两种情况的
 1、我希望私聊的时候，可以不加@，这时候直接输入就可以，这个可以用robot.hear处理；
 2、在群聊时，收到的消息又分为两种，
        （1）带@的，可以交个robot.respond处理
        （2）不带@的，这个直接忽略，但是在满足1 的前提下，这一条不能满足，因为在后端的script中无法区分是群聊还是私聊。

**Comment by KasperDeng** [comment]
明白你的意思了。但其实是可以区分的。在后端的script里面，callback的入参其实是带上了消息的来源的，你可以在调试过程中打印看看。
其中有个属性`envelope`，带了两属性
- `room`：在hubot-weixin里面，这个是群的`uin`。如果私聊的话，就是空值。
- `user`：在hubot-weixin里面，如果是群聊，这个是群里面发言的用户的`uin`。如果是私聊，就是那用户的`uin`了。
至于，怎么区分群和用户的`uin`，在微信里面应该不用多说了吧？

**Comment by lihk11** [comment]
OK
