### ISSUE TITLE
ERROR Cannot load adapter weixin - SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by gztitan** [KasperDeng/Hubot-WeChat#13]
@KasperDeng 有否配置上HEROKU，似乎不支持！（i am not sure if need to enable some of the ECMAScript 2015 features (including const and let), 可能你需要enhance this issue!

met the subject issue as below:
When I deployed it to Heroku that met subject error. and even I had been went through the below steps:

npm cache clean -f
npm install -g n
n stable

it still doesn't work.  

after debug at bash model and found:
/app/node_modules/file-md5/index.js:3
const fs = require('fs');
^^^^^
[Tue Jun 28 2016 08:01:20 GMT+0000 (UTC)] ERROR Cannot load adapter weixin - SyntaxError: Use of const in strict mode.

**Comment by gztitan** [comment]
The issue was fixed by revised Node engine version in the package.json in project-base, which turned up to upper 4.X as it was 0.10.6 before.

**Comment by hanyan007** [comment]
@gztitan 具体怎么解决的，能说明下吗？谢谢
