### ISSUE TITLE
about hubot-ece

### ISSUE THREAD

**Issue by mattun** [KasperDeng/Hubot-WeChat#4]
I did bin/hubot -a weixin
but apear
[Thu Apr 28 2016 19:31:03 GMT+0800 (CST)] ERROR Cannot load adapter weixin - Error: ENOENT: no such file or directory, open './node_modules/hubot-ece/config.yaml'

then I tried search hubot-ece , but couldn't find.
it must replace another??

Thanks

**Comment by KasperDeng** [comment]
Hi mattun. Not sure what version you were used to setup the hutbot-weixin. Please also check the change in this [commit](https://github.com/KasperDeng/Hubot-WeChat/commit/023dbfff91564d076f551e46917353e2eb981efc)
or check your src/config.coffee, update `hubot-ece` to `hubot-weixin`. Hope it helps. Thanks!
