### ISSUE TITLE
发送图片出现错误

### ISSUE THREAD

**Issue by ctgnauh** [KasperDeng/Hubot-WeChat#6]
提示：

`Upload media failed, RC 1100`

**Comment by KasperDeng** [comment]
刚刚更新了代码，微信的`webwxuploadmedia`和`webwxsendmsgimg`略有更改。请更新再试试。等下我会发布到npm上，版本1.0.5。
另外，要注意`config.yaml`里面的`aseUploadUrl: "https://file2.wx.qq.com/cgi-bin/mmwebwx-bin"`，要确保用作hubot的微信号所用的url。这里可以是`file`或`file2`。原因和`wx`与`wx2`一样，微信做了服务分流。

**Comment by ctgnauh** [comment]
非常感谢，问题已经修正了。
