### ISSUE TITLE
如何与百度api商店的查询和图灵接口集成

### ISSUE THREAD

**Issue by gztitan** [KasperDeng/Hubot-WeChat#9]
源程序中似乎没有相应的代码在readme 中提到的：“提供了一系列的后端运行脚本
集成 jenkins
集成图灵机器人 turing robot
一系列的百度api商店的查询接口集成“。。。。。

请问如何实现？

**Comment by xxlv** [comment]
@gztitan weixin这个adapter里面没有具体对某个脚本的实现，你可以写你自己的脚本来实现。一个简单的图灵机器人的脚本像是这样：

`robot.hear /(.*?)/, (res)->
        input=res.match['input']
        turingurl=BAIDU_TURING_URL+'?key='+BAIDU_TURING_KEY+'&info='+input+"&userid="+res.envelope.user.id
        robot.http(turingurl).header('apikey',BAIDU_API_KEY).get() (e,r,b)->
        
            if (!input.match(/&lt;msg/))
                b=JSON.parse b
                setTimeout ()->
                    res.send b.text
                , 1000`

**Comment by KasperDeng** [comment]
我前段时间将后端的脚本移到新的repo下了，因为夹带这些后端脚本，不方面我发布到npm。请移玉步到[Hubot-Scripts](https://github.com/KasperDeng/Hubot-Scripts) 参考。这里面有关于简介里面提到的一系列脚本。
* 集成注意的地方
  - 不论是百度商店还是图灵，都需要你到百度商店或图灵注册认证账号，才能拿到他们授权的api key。
  - 集成测试，可以先用hubot shell来验证api的访问和回应，无需用微信hubot来测，省事很多。
  - 大部分的api回应应该都是基于json的，而且尽量用json的api，少用xml的。另外有些json的reponse在用`JSON.parse()`的时候会出错，主要是服务器回应的json有点问题，和`JSON.parse`不兼容，可以尝试用`eval`来解决。

**Comment by gztitan** [comment]
正啊！感谢楼主的回复

**Comment by KasperDeng** [comment]
不用这么麻烦。就在你的hubot(**注意** 是hubot，不是指hubot-weixin这个adapter)的目录下，创建`scrips`目录，把所有的`*.coffee`脚本放进去就可以。hubot启动的时候会从这个目录load脚本进去的。

**Comment by gztitan** [comment]
@KasperDeng , 您好，
不知为何那图灵机器人没有反应，我的设置如下：
key = "图灵APIkey"
userid = "微信用户号"

使用命令“hubot 图灵 你好”
图灵机器人账号等级:免费版会员
先谢谢！

**Comment by gztitan** [comment]
搞掂了！ @KasperDeng，原来我的图灵机器人开启了加密模式。谢谢！加“星”

**Comment by KasperDeng** [comment]
谢谢。另外，我更新了下后端图灵的脚本，加上了try...catch...。因为最近看到连图灵服务器失败的时候，后端脚本出了exception，会把hubot抛死了。
所以我建议，后端的脚本的异常处理一定要做。

**Comment by gztitan** [comment]
明白，谢谢

**Comment by gztitan** [comment]
@KasperDeng 
发现加了异常处理之后，似乎有些信息不能在微信上显示，不过后台已经出来了。
